# Generated by Django 5.2.3 on 2025-06-29 20:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stajyer',
                'verbose_name_plural': 'Stajyerler',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Proje Adı')),
                ('short_description', models.TextField(verbose_name='Kısa Açıklama')),
                ('full_description', models.TextField(help_text='HTML formatında yazabilirsiniz.', verbose_name='Detaylı Açıklama')),
                ('team_size', models.CharField(choices=[('1', '1 Kişilik'), ('2-3', '2-3 Kişilik'), ('3-4', '3-4 Kişilik'), ('4+', '4+ Kişilik')], default='2-3', max_length=10, verbose_name='Ekip Büyüklüğü')),
                ('work_type', models.CharField(choices=[('remote', 'Uzaktan Çalışma'), ('hybrid', 'Hibrit Çalışma'), ('office', 'Ofisten Çalışma')], default='remote', max_length=10, verbose_name='Çalışma Şekli')),
                ('duration', models.CharField(choices=[('2', '2 Ay'), ('3', '3 Ay'), ('4', '4 Ay')], default='3', max_length=5, verbose_name='Staj Süresi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
            },
        ),
        migrations.CreateModel(
            name='ProjectPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('first_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_choices', to='intern_portal.project')),
                ('intern', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='intern_portal.intern')),
                ('second_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_choices', to='intern_portal.project')),
                ('third_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_choices', to='intern_portal.project')),
            ],
            options={
                'verbose_name': 'Proje Tercihi',
                'verbose_name_plural': 'Proje Tercihleri',
            },
        ),
    ]
