# Generated by Django 5.2.3 on 2025-07-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InternAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "availability_data",
                    models.JSONField(
                        default=dict,
                        help_text='JSON formatında haftalık müsaitlik verileri. Format: {"monday": ["09:00", "10:00", ...], "tuesday": [...], ...}',
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "intern",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="intern_portal.intern",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stajyer Müsaitlik",
                "verbose_name_plural": "Stajyer Müsaitlikleri",
            },
        ),
    ]
