# Generated by Django 5.2.3 on 2025-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0002_internavailability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internavailability",
            options={
                "verbose_name": "Stajyer Ortak Çalışma Saati",
                "verbose_name_plural": "Stajyer Ortak Çalışma Saatleri",
            },
        ),
        migrations.AlterField(
            model_name="internavailability",
            name="availability_data",
            field=models.JSONField(
                default=dict,
                help_text='JSON formatında haftalık ortak çalışma saati verileri. Format: {"monday": ["09:00", "10:00", ...], "tuesday": [...], ...}',
            ),
        ),
    ]
