# Generated by Django 5.2.3 on 2025-07-17 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0003_alter_internavailability_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="intern",
            options={
                "ordering": ["first_name", "last_name"],
                "verbose_name": "Stajyer",
                "verbose_name_plural": "Stajyerler",
            },
        ),
        migrations.AddField(
            model_name="intern",
            name="assigned_projects",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bu stajyere atanmış projeler (admin tarafından)",
                related_name="assigned_interns",
                to="intern_portal.project",
                verbose_name="Atanmış Projeler",
            ),
        ),
        migrations.AddField(
            model_name="intern",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="access_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Erişim Token",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-posta"
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="Ad"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktif"),
        ),
        migrations.AlterField(
            model_name="intern",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="Soyad"),
        ),
        migrations.AlterField(
            model_name="internavailability",
            name="availability_data",
            field=models.JSONField(
                default=dict,
                help_text='JSON formatında haftalık ortak çalışma saati verileri. Format: {"monday": ["09:00-10:00", "10:00-11:00", ...], "tuesday": [...], ...}',
            ),
        ),
    ]
