# Generated by Django 5.2.3 on 2025-07-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intern_portal",
            "0005_availabilitysettings_internavailability_is_locked_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="availabilitysettings",
            name="minimum_hours_required",
        ),
        migrations.RemoveField(
            model_name="internavailability",
            name="availability_data",
        ),
        migrations.AddField(
            model_name="availabilitysettings",
            name="group_meeting_hours_min",
            field=models.PositiveIntegerField(
                default=20,
                help_text="Minimum required group meeting hours (09:00-17:00) per week",
                verbose_name="Minimum Group Meeting Hours",
            ),
        ),
        migrations.AddField(
            model_name="availabilitysettings",
            name="individual_work_hours_min",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minimum required individual work hours (any time) per week",
                verbose_name="Minimum Individual Work Hours",
            ),
        ),
        migrations.AddField(
            model_name="internavailability",
            name="group_meeting_data",
            field=models.JSONField(
                default=dict,
                help_text='JSON formatında grup toplantı saatleri (09:00-17:00). Format: {"monday": ["09:00-10:00", "10:00-11:00", ...], "tuesday": [...], ...}',
            ),
        ),
        migrations.AddField(
            model_name="internavailability",
            name="individual_work_data",
            field=models.JSONField(
                default=dict,
                help_text='JSON formatında bireysel çalışma saatleri (24 saat). Format: {"monday": ["00:00-01:00", "01:00-02:00", ...], "tuesday": [...], ...}',
            ),
        ),
    ]
