# Generated by Django 5.2.3 on 2025-07-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "intern_portal",
            "0006_remove_availabilitysettings_minimum_hours_required_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Stajyer profil fotoğrafı (opsiyonel)",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
