# Generated by Django 5.2.3 on 2025-07-19 13:47

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0007_intern_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="intern",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "profile_picture",
                "350x350",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text="Profil fotoğrafını kare şeklinde kırpmak için kullanın",
                hide_image_field=False,
                size_warning=False,
                verbose_name="Fotoğraf Kırpma",
            ),
        ),
        migrations.AlterField(
            model_name="intern",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Stajyer profil fotoğrafı (opsiyonel) - Yükleme sonrası kırpma yapabilirsiniz",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
