# Generated by Django 5.2.3 on 2025-07-19 15:51

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0008_intern_cropping_alter_intern_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intern",
            name="profile_picture",
            field=image_cropping.fields.ImageCropField(
                blank=True,
                help_text="Stajyer profil fotoğrafı (opsiyonel) - Yükleme sonrası kırpma yapabilirsiniz",
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
