# Generated by Django 5.2.3 on 2025-07-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intern_portal", "0009_alter_intern_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intern",
            name="cropping",
        ),
        migrations.AlterField(
            model_name="intern",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pics/",
                verbose_name="Profil Fotoğrafı",
            ),
        ),
    ]
